// packages/app/src/solid/FileDropdown.tsx
import { For, Show } from "solid-js"

import { editor } from "$/app/editor"
import { Actions, DropdownLabel, FILE_ICON, on, tracked } from "$/app/solid"

import "./FileDropdown.css"

/****************
 * ### `<FileDropdown>`
 * Menu of all available files for the selected project (`editor.project`):  a `<ui-dropdown>` of `<ui-item>`s,
 * showing `editor.file`.  Same props as React's `UI.FileDropdown` had.
 * - Choosing a file shows it in `<SpellEditor>`, or `<SpellRunner>` with `useRunner`.
 * - Loading (spinning caret, no items) until the project's loaded and has a file.
 * - The dropdown's value is ALWAYS `editor.file`'s path:  choosing sets it back during the event, and shows the file
 *   chosen, which then becomes `editor.file` (see `choose()`).
 * - `showActions`:  `Actions.FILE_DROPDOWN_ACTIONS` after a divider, as dropdown items;  choosing
 *   one clicks it, as `<MoreMenu>` does.
 * - Sits in a menu:  wrapped in a `<ui-item class="FileDropdown">`.  Look:  `FileDropdown.css`.
 ****************/
export function FileDropdown(props: FileDropdownProps) {
  /** What it shows, read from `editor` in one go. */
  const state = tracked(() => {
    const { project, file } = editor
    const ready = !!project?.isLoaded && !!file
    return {
      ready,
      path: file?.path ?? "",
      files: ready ? project.imports.map(({ path, location }) => ({ path, name: location.file })) : []
    }
  })

  return (
    <>
      <Show when={props.showLabel ?? true}>
        {/* HACK: a slotted `<ui-icon>`, not `icon`:  see `<Action>` */}
        <DropdownLabel>
          <ui-icon name={FILE_ICON} />
          File:
        </DropdownLabel>
      </Show>
      <ui-item class="FileDropdown">
        <ui-dropdown
          id="FileDropdown"
          class="FileDropdown"
          loading={!state().ready}
          prop:value={state().path}
          ref={on<{ value: string }>("ui-change", choose)}
        >
          <For each={state().files} keyed={(file) => file.path}>
            {(file) => (
              <ui-item value={file().path} icon={FILE_ICON} onClick={() => open(file().path)}>
                {file().name}
              </ui-item>
            )}
          </For>
          <Show when={props.showActions && state().ready}>
            <ui-item type="divider" />
            <Actions.FILE_DROPDOWN_ACTIONS />
          </Show>
        </ui-dropdown>
      </ui-item>
    </>
  )

  /** Show the file at `path`, in the editor or the runner. */
  function open(path: string) {
    if (props.useRunner) void editor.showRunner(path)
    else editor.showEditor(path)
  }
}

/** Props for `<FileDropdown>`. */
export type FileDropdownProps = {
  /** Open `<SpellRunner>` instead of `<SpellEditor>` when an item is clicked. */
  useRunner?: boolean
  /** Put a `<DropdownLabel>` before the dropdown.  Default:  `true`. */
  showLabel?: boolean
  /** Append `Actions.FILE_DROPDOWN_ACTIONS` after a divider. */
  showActions?: boolean
}

/**
 * The dropdown's `ui-change`:  click the item chosen -- a file's opens it, an action's runs it.
 * - SIDE EFFECT:  sets the dropdown's `value` back to `editor.file`'s DURING the event, so the dropdown keeps ours:
 *   the host decides (`Controlled`, `packages/ui/src/elements/Controlled.ts`).  Opening the file then moves it on.
 */
function choose(event: CustomEvent<{ value: string }>) {
  const dropdown = event.currentTarget as HTMLElement & { value?: unknown }
  dropdown.value = editor.file?.path ?? ""
  const item = [...dropdown.children].find(
    (child) =>
      child.localName === "ui-item" && (child.getAttribute("value") ?? child.textContent?.trim()) === event.detail.value
  )
  ;(item as HTMLElement | undefined)?.click()
}

// packages/app/src/ui/FileDropdown.tsx
/** @jsxImportSource react */
import React from "react"
import * as SUI from "semantic-ui-react"

import { view } from "$/util"
import type { SP } from "$/spell"

import { editor } from "$/app/editor"

import { UI } from "$/app/ui"
import { Actions } from "./Actions"

/****************
 * ### `<FileDropdownAction>`
 * Single item in `<FileDropdown>`'s menu, for one file `path` in the current project.
 ****************/
const FileDropdownAction = React.memo(({ useRunner, path, location, active }: FileDropdownActionProps) => (
  <SUI.Dropdown.Item
    text={location.file}
    value={path}
    icon={UI.FILE_ICON}
    active={active}
    onClick={() => (useRunner ? editor.showRunner(path) : editor.showEditor(path))}
  />
))

/** Props for `<FileDropdownAction>`. */
export type FileDropdownActionProps = {
  /** Open `<SpellRunner>` instead of `<SpellEditor>` when clicked. */
  useRunner: boolean
  /** File path this item selects. */
  path: string
  /** Parsed location for `path`, used to show its file name. */
  location: SP.SpellLocation
  /** Whether this is `editor.file`, the currently selected file. */
  active: boolean
}

/****************
 * ### `<FileDropdown>`
 * Menu of all available files for the selected project (`editor.project`).
 ****************/
export const FileDropdown = view(function FileDropdown({
  useRunner = false,
  showLabel = true,
  showActions = false
}: FileDropdownProps) {
  const { project, file }: { project?: SP.SpellProject; file?: SP.AnySpellFile } = editor
  const ready = project?.isLoaded && !!file
  const dropdownProps: SUI.DropdownProps = {
    id: "FileDropdown",
    basic: true,
    item: true,
    text: ready ? file.file : "",
    loading: !ready,
    lazyLoad: true,
    labeled: true,
    style: { minWidth: "8em", fontWeight: 700 }
  }
  if (ready && project) {
    const menuItems: ReactElement[] = project.imports.map(({ path, location }) => (
      <FileDropdownAction
        key={path}
        useRunner={useRunner}
        path={path}
        location={location}
        active={path === file.path}
      />
    ))
    if (showActions && Actions.FILE_DROPDOWN_ACTIONS) {
      menuItems.push(<SUI.Dropdown.Divider key="divider" />, ...Actions.FILE_DROPDOWN_ACTIONS)
    }
    dropdownProps.children = <SUI.Dropdown.Menu>{menuItems}</SUI.Dropdown.Menu>
  }
  const dropdown = <SUI.Dropdown {...dropdownProps} />
  if (!showLabel) return dropdown
  return (
    <>
      <UI.DropdownLabel title="File:" icon={UI.FILE_ICON} />
      {dropdown}
    </>
  )
})

/** Props for `<FileDropdown>`. */
export type FileDropdownProps = {
  /** Open `<SpellRunner>` instead of `<SpellEditor>` when an item is clicked. */
  useRunner?: boolean
  /** Prepend a `<UI.DropdownLabel>` before the dropdown. */
  showLabel?: boolean
  /** Append `Actions.FILE_DROPDOWN_ACTIONS` after a divider. */
  showActions?: boolean
}
