// packages/app/src/solid/SpellPage.tsx
import { omit } from "solid-js"
import type { JSX } from "@solidjs/web"

import "./spell.css"
import "./SpellPage.css"

/****************
 * ### `<SpellPage>`
 * A whole page's box:  look variants (bordered, dark, light, rounded, spaced, padded, scrolling) and, with `rows` /
 * `columns`, a flexbox laying `children` out down or across the page.  Look:  `SpellPage.css`.
 * - Every other prop (`id`, `style`, `aria-*` ...) goes to the `<div>`.
 ****************/
export function SpellPage(props: SpellPageProps) {
  return (
    <div
      {...omit(props, ...VARIANTS, "class", "children")}
      class={[
        "SpellPage",
        {
          bordered: !!props.bordered,
          dark: !!props.dark,
          "fill-window": !!props.fillWindow,
          light: !!props.light,
          rounded: !!props.rounded,
          spaced: !!props.spaced,
          padded: !!props.padded,
          scrolling: !!props.scrolling,
          rows: !!props.rows,
          columns: !!props.columns
        },
        props.class
      ]}
    >
      {props.children}
    </div>
  )
}

/** Props for `<SpellPage>`:  these, plus any `<div>` attribute. */
export type SpellPageProps = JSX.HTMLAttributes<HTMLDivElement> & {
  /** Bordered variant. */
  bordered?: boolean
  /** Dark variant. */
  dark?: boolean
  /** Fill the window:  `position: absolute`, `100vw` x `100vh`. */
  fillWindow?: boolean
  /** Light variant. */
  light?: boolean
  /** Rounded variant. */
  rounded?: boolean
  /** Spacing around the page. */
  spaced?: boolean
  /** Padding inside the page. */
  padded?: boolean
  /** Scrolls its content. */
  scrolling?: boolean
  /** Lay `children` out in rows, down the page (flexbox). */
  rows?: boolean
  /** Lay `children` out in columns, across the page (flexbox). */
  columns?: boolean
}

/** `<SpellPage>`'s own props:  the look, never passed to the `<div>`. */
const VARIANTS = [
  "bordered",
  "dark",
  "fillWindow",
  "light",
  "rounded",
  "spaced",
  "padded",
  "scrolling",
  "rows",
  "columns"
] as const

// packages/app/src/ui/SpellPage.tsx
/** @jsxImportSource react */
import React from "react"
import classnames from "classnames"

import "./SpellPage.css"

/****************
 * ### `<SpellPage>`
 * Generic full-page layout wrapper -- presentational style variants (bordered / dark / light / rounded /
 * spaced / padded / scrolling) plus optional flexbox row/column layout for `children`.  Styled by
 * `./SpellPage.css`.
 * TODOC!
 ****************/
export function SpellPage(props: SpellPageProps) {
  const {
    bordered = false, // bordered variant
    dark = false, // dark variant
    fillWindow = false, // fill window completely.  alias for `full`
    light = false, // light variant
    rounded = false, // rounded variant
    spaced = false, // spaced variant (around page)
    padded = false, // padding (within page)
    scrolling = false, // scrolling variant
    rows = false, // use flexbox to lay children out in rows, down the page.
    columns = false, // use flexbox to lay children out in columns, across the page.
    // other props, e.g. `children`, id`, `style`, aria-stuff, etc...
    ...renderProps
  } = props

  const className = classnames(
    {
      bordered,
      dark,
      "fill-window": fillWindow,
      rows,
      columns,
      light,
      rounded,
      spaced,
      padded,
      scrolling
    },
    "SpellPage",
    renderProps.className
  )
  return <div {...renderProps} className={className} />
}

/** Props for `<SpellPage>`.  Extra keys (`children`, `id`, `style`, aria-*, ...) pass through to the `<div>`. */
export type SpellPageProps = React.ComponentPropsWithoutRef<"div"> & {
  /** Bordered variant. */
  bordered?: boolean
  /** Dark variant. */
  dark?: boolean
  /** Fill window completely, via `.fill-window` in `$/app/ui/SpellPage.css`. */
  fillWindow?: boolean
  /** Light variant. */
  light?: boolean
  /** Rounded variant. */
  rounded?: boolean
  /** Spaced variant (around page). */
  spaced?: boolean
  /** Padding (within page). */
  padded?: boolean
  /** Scrolling variant. */
  scrolling?: boolean
  /** Use flexbox to lay `children` out in rows, down the page. */
  rows?: boolean
  /** Use flexbox to lay `children` out in columns, across the page. */
  columns?: boolean
}
