// packages/app/src/ui/AppRoot.tsx
/** @jsxImportSource react */
import React from "react"

import { editor } from "$/app/editor"
import { UI } from "$/app/ui"
import { Actions } from "./Actions"
import { AppContainer } from "./AppContainer"

import "./AppRoot.css"

/****************
 * ### `<AppRoot>`
 * Top-level wrapper for the compiled spell app: an optional `<AppToolbar>` plus `<AppContainer>`.
 * - Its mount point is where `editor` runs programs -- see `editor.setAppRoot()`.
 ****************/
export const AppRoot = React.memo(function AppRoot({
  showToolbar = true,
  scrolling = true,
  padded = true
}: AppRootProps) {
  return (
    <div className="AppRoot">
      {!!showToolbar && <AppToolbar />}
      <AppContainer scrolling={scrolling} padded={padded} appRef={editor.setAppRoot} />
    </div>
  )
})

/** Props for `<AppRoot>`. */
export type AppRootProps = {
  /** Show `<AppToolbar>` above `<AppContainer>`.  Defaults `true`. */
  showToolbar?: boolean
  /** Passed through to `<AppContainer>`. */
  scrolling?: boolean
  /** Passed through to `<AppContainer>`. */
  padded?: boolean
}

/****************
 * ### `<AppToolbar>`
 * Toolbar shown above the running app: restart / publish actions, plus a stubbed "..." menu.
 ****************/
export function AppToolbar() {
  return (
    <UI.PanelMenu>
      <UI.Submenu left spring>
        <UI.MenuHeader content="App" />
      </UI.Submenu>
      <UI.Submenu right spring>
        <Actions.restartApp />
        {/* <Actions.showRunner /> */}
        <Actions.publishApp />
        <UI.MoreMenu stub />
      </UI.Submenu>
    </UI.PanelMenu>
  )
}

// packages/app/src/solid/AppRoot.tsx
import { Show, onCleanup } from "solid-js"

import { editor } from "$/app/editor"
import { Actions, MenuHeader, MoreMenu, PanelMenu, Submenu } from "$/app/solid"
import { AppContainer } from "./AppContainer"

import "./AppRoot.css"

/****************
 * ### `<AppRoot>`
 * The running program in the editor's pages:  an optional `<AppToolbar>` above an `<AppContainer>`.
 * - SIDE EFFECT:  its container is where `editor` runs programs (`editor.setAppRoot()`), until it goes
 *   (`editor.releaseAppRoot()`).
 ****************/
export function AppRoot(props: AppRootProps) {
  let appElement: HTMLDivElement | undefined
  onCleanup(() => {
    if (appElement) editor.releaseAppRoot(appElement)
  })
  return (
    <div class="AppRoot">
      <Show when={props.showToolbar ?? true}>
        <AppToolbar />
      </Show>
      <AppContainer
        scrolling={props.scrolling ?? true}
        padded={props.padded ?? true}
        appRef={(element) => {
          appElement = element
          editor.setAppRoot(element)
        }}
      />
    </div>
  )
}

/** Props for `<AppRoot>`. */
export type AppRootProps = {
  /** Show `<AppToolbar>` above the program.  Default:  `true`. */
  showToolbar?: boolean
  /** Scrolls the program's drawing.  Default:  `true`. */
  scrolling?: boolean
  /** Padding around the program's drawing.  Default:  `true`. */
  padded?: boolean
}

/****************
 * ### `<AppToolbar>`
 * Toolbar above the running program:  restart and publish, and a stub "..." menu.
 ****************/
export function AppToolbar() {
  return (
    <PanelMenu>
      <Submenu left spring>
        <MenuHeader>App</MenuHeader>
      </Submenu>
      <Submenu right spring>
        <Actions.restartApp />
        <Actions.publishApp />
        <MoreMenu stub />
      </Submenu>
    </PanelMenu>
  )
}
