// packages/app/src/ui/SplitPanel.tsx
/** @jsxImportSource react */
import React from "react"
import classnames from "classnames"

import { getPadding, getPref, setPref, resetPref } from "$/util"

import "./SplitPanel.css"

/****************
 * ### `<SplitPanel>`
 * Manages its `children` to set their sizes.
 * - Specify child sizes as EITHER `rows` or `columns` as:
 *   - `true` to give each child equal size, or
 *   - an array like: `["20%", "20%", "*", 100]`, or
 *   - a string like `30%,2em`.
 * - Panels will be sized like so:
 *   - numbers without units, or with units `px`, `em`, `rem`:  fixed size panel.
 *   - numbers with units of `%`:  will take up that percent of non-fixed space.
 *   - `*` or not specified:  Split left-over percentage of space equally amongst all `*` children.
 *   e.g. `80%,20%` (same as just `80%` for 2 panes)
 *   e.g. `*,*,200px` (same as `50%,50%,200px`)
 * - Provided `children` will be automatically wrapped in `<SplitPane>` elements,
 *   with `bordered`, `padded`, `light`, `rounded` and `scrolling` applied as set on the panel.
 *   You can manually wrap a child in a `<SplitPane>` to overide panel-level settings.
 * - If `<SplitPanel resizable />` we'll put `<SplitSizer>` elements in between provided children.
 *   If `<SplitPanel spaced />` we'll put `<SplitSpacer>` elements in between provided children,
 *   as well as add spacing around the children.
 * - Resizble `<SplitPanel>`s will automatically remember their sizes as "preferences"
 *   if you specify an `id` property.  It's up to you to make this unique for your app.
 * - If you have a pointer to a `<SplitPanel>`, you can have it `updateSizes()` with a size string.
 ****************/
export class SplitPanel extends React.Component<SplitPanelProps> {
  /** Alias for `SplitPane`, so consumers can write `<SplitPanel.Pane>`. */
  declare static Pane: typeof SplitPane
  /** Alias for `SplitSpacer`, so consumers can write `<SplitPanel.Spacer>`. */
  declare static Spacer: typeof SplitSpacer
  /** Alias for `SplitSizer`, so consumers can write `<SplitPanel.Sizer>`. */
  declare static Sizer: typeof SplitSizer

  /** Ref to the panel.  We use this to get pane elements for dynamic sizing. */
  ref = React.createRef<HTMLDivElement>()

  /** Get pointers to all of our pane elements, or an empty array if we haven't drawn yet. */
  get paneElements(): HTMLElement[] {
    if (!this.ref.current) return []
    return Array.from(this.ref.current.querySelectorAll<HTMLElement>(":scope > *[data-pane]"))
  }

  /** Get a particular panel element by `index`. */
  getPane(index: number): HTMLElement | undefined {
    return this.paneElements[index]
  }

  /** Sync pane DOM elements to `sizes` once mounted. */
  componentDidMount() {
    this.updateSizes()
  }

  /** Re-sync pane DOM elements to `sizes` after any update -- props/children may have changed. */
  componentDidUpdate() {
    this.updateSizes()
  }

  /**
   * Wrap `children` in `<SplitPane>`s (cloning `props` onto ones already provided), inserting
   * `<SplitSizer>`/`<SplitSpacer>` between them per `resizable`/`spaced`, and load initial `sizes`.
   */
  render() {
    const {
      children,
      columns, // column sizes for horizontal split, as `true`, string or array.  See `normalizeSizes()`.
      rows, // row sizes for vertical split, as `true`, string or array.  See `normalizeSizes()`.
      fluid = false, // fill container in alternate axis?
      spaced = false, // spacing around and between children. `true`, "tightly", "loosely" ???
      resizable = false, // provide resize bars.  Will store `sizes` as preference if element has an `id`.
      minSize: _minSize = 5, // minimum percent size for resizable panels

      // The following will be passed down to SplitPanes which are automatically created.
      // If you create a <SplitPane> manually, these settings are ignored.
      bordered, // panes are borderd
      padded, // padding in panes
      light, // panes appeear light
      rounded, // panes appear rounded
      scrolling, // provide scrollbars in panes

      // other props, e.g. `id`, `style`, aria-stuff, etc...
      ...renderProps
    } = this.props

    if ((!columns && !rows) || (columns && rows)) {
      console.warn("<SplitPanel>s must be initialized with exactly one of 'columns' or 'rows'.", this.props)
    }

    // Load our `sizes` or calculate based on props
    this.loadSizes()

    const className = classnames(
      {
        fluid,
        tightly: spaced === "tightly",
        loosely: spaced === "loosely",
        spaced,
        resizable
      },
      this.direction,
      "SplitPanel",
      renderProps.className
    )

    const kids: ReactNode[] = []
    const kidProps = { bordered, padded, light, rounded, scrolling }
    React.Children.forEach(children, (child, index) => {
      // add resizer or spacer
      if (index !== 0) {
        if (resizable) {
          kids.push(
            <SplitSizer key={`sizer-${index - 1}`} onMouseDown={(event) => this.onMouseDown(event, index - 1, index)} />
          )
        } else if (spaced) {
          kids.push(<SplitSpacer key={`spacer-${index}`} />)
        }
      }

      if (React.isValidElement(child) && (child.type === SplitPane || child.type === SplitPanel)) {
        const cloneProps = {
          key: `panel-${index}`,
          ...(child.type === SplitPane ? kidProps : undefined),
          ...(child.props as object),
          "data-pane": index
        }
        kids.push(React.cloneElement(child, cloneProps))
      } else {
        kids.push(
          <SplitPane key={`panel-${index}`} {...kidProps} data-pane={index}>
            {child}
          </SplitPane>
        )
      }
    })
    return (
      <div ref={this.ref} {...renderProps} className={className}>
        {kids}
      </div>
    )
  }

  ////////////////
  // ## Size logic and calculations
  ////////////////

  /**
   * Currently calculated `sizes`, updated when drawn and on resize.
   * NOTE: we don't store sizes in state because we update it during drag-resize.
   */
  sizes: PanelSize[] | undefined = undefined

  /** Return our current sizes as a string. */
  get sizeString(): string {
    if (!this.sizes) return ""
    return this.sizes.map(({ value, units }) => `${value}${units}`).join(",")
  }

  /** Preference name for our sizes.  May be `undefined`. */
  get sizesPref(): string | undefined {
    return this.props.id
  }

  /** Load normalized `sizes`, or, if not stored, calculate them based on our `props`. */
  loadSizes(): void {
    const sizesPref = this.sizesPref
    const sizeString = (sizesPref && getPref(sizesPref, undefined)) || this.props.columns || this.props.rows
    this.sizes = SplitPanel.normalizeSizes(sizeString, this.props.children)
    //console.warn(sizeString, this.sizes)
  }

  /** Reset our `sizes` to our "factory defaults". */
  resetSizes(): void {
    // clear old value
    if (this.sizesPref) resetPref(this.sizesPref)
    this.loadSizes()
    this.updateSizes()
  }

  /** Save normalized `sizes` as a preference. */
  saveSizes(): void {
    if (this.sizesPref) setPref(this.sizesPref, this.sizeString)
  }

  /**
   * Update geometry of our `paneElements` to match `sizes`.
   * Called after draw and during resize to update pane sizes.
   *
   * You can pass a string and we'll normalize for you.
   */
  updateSizes = (sizes: PanelSize[] | string | undefined = this.sizes): void => {
    let resolvedSizes: PanelSize[]
    if (typeof sizes === "string") {
      resolvedSizes = SplitPanel.normalizeSizes(sizes, this.props.children)
    } else {
      resolvedSizes = sizes || []
      if (resolvedSizes !== this.sizes) {
        this.sizes = resolvedSizes
        this.saveSizes()
      }
    }
    this.paneElements?.forEach((pane, index) => {
      const size = resolvedSizes[index]
      if (!size) return
      const { value, units } = size
      const flex = units === "%" ? `${value} ${value} 0` : `0 0 ${value}${units}`
      pane.style.flex = flex
    })
  }

  /** Matches a single size token, e.g. `20`, `20px`, `20%` -- captures numeric value and optional units. */
  static NUM_WITH_UNITS_PATTERN = /^([0-9]*\.?[0-9]+)(px|em|rem|%)?$/

  /**
   * Convert raw `startSizes` (a `columns`/`rows` spec: `true`, a `"20%,2em,*"` string, or an array)
   * into one `PanelSize` per child, padding/truncating to `children`'s count and defaulting missing
   * or unparseable entries to `*`.
   * - `*` entries share the percentage left over after fixed (`px`/`em`/`rem`) and `%` entries are subtracted.
   */
  static normalizeSizes(startSizes: unknown = [], children: ReactNode): PanelSize[] {
    // TODO: `hidden` children shouldn't be counted!
    //  BUT: make sure we keep an entry in the array for them!!!
    // TODO: take `minSize` for child elements into account
    const childCount = React.Children.count(children)

    let inputSizes: (string | number)[]
    if (typeof startSizes === "string" && startSizes) inputSizes = startSizes.split(",")
    else if (Array.isArray(startSizes)) inputSizes = startSizes as (string | number)[]
    else inputSizes = []

    const sizes: (string | number)[] = inputSizes.slice(0, childCount)
    if (sizes.length < childCount) {
      const start = sizes.length - childCount
      sizes.length = childCount
      sizes.fill("*", start)
    }

    // normalize `sizes` to `{ number, units }`
    let starCount = 0
    let percents = 0
    const normalized: { value: number | "*"; units: string }[] = sizes.map((size) => {
      if (typeof size === "number") return { value: size, units: "px" }
      if (size !== "*") {
        const match = SplitPanel.NUM_WITH_UNITS_PATTERN.exec(size)
        if (match) {
          const [, num, unitsMatch] = match
          const units = unitsMatch || "px"
          const value = parseFloat(num)
          if (units === "%") percents += value
          return { value, units }
        }
        console.warn(`Start size '${size}' not understood`)
      }
      starCount++
      return { value: "*" as const, units: "%" }
    })
    if (starCount) {
      const valuePerStar = Math.max(1, (100 - percents) / starCount)
      normalized.forEach((size) => {
        if (size.value === "*") size.value = valuePerStar
      })
    }
    return normalized as PanelSize[]
  }

  ////////////////
  // ## Event handlers and utilites for resizing
  ////////////////

  /** Return our `direction`. */
  get direction(): "horizontal" | "vertical" {
    return this.props.columns ? "horizontal" : "vertical"
  }

  /** Return min-size for one of our panels, AS A PERCENTAGE. */
  get minPercent(): number {
    return this.props.minSize || 5
  }

  /**
   * Return `dimensions` for sizing calculations, according to our `direction`.
   * Believe it or not, we actually need to figure out all of the below.
   *
   * We'll catch any errors if this throws, so don't worry if DOM is not ready etc.
   *
   * Called `onMouseDown` and cached.
   * Unfortunately, `getBoundingClientRect()` is very slow, so we can't call this every `mouseMove`.
   * That means if the window scrolls while the mouse is down, we're screwed.
   * If we need to account for that, we COULD check periodically check `window.scrollX`/`.scrollY`
   * and get the dimensions again if they change.
   */
  getSizingDimensions(pane1: number, pane2: number): SplitPanelDimensions {
    const { sizes, direction, paneElements, minPercent } = this

    const pane1El = paneElements[pane1]
    const pane2El = paneElements[pane2]

    // TODO: this will be off if CSS transform has been applied to the panel.
    const rect1 = pane1El.getBoundingClientRect()
    const rect2 = pane2El.getBoundingClientRect()

    // page min / max value in appropriate direction
    const vertical = direction === "vertical"
    const pageMin = vertical ? rect1.top : rect1.left
    const pageMax = vertical ? rect2.bottom : rect2.right

    // gap between the two elements, then gapOffset we'll use for mouse adjustments
    const gap = Math.ceil(vertical ? rect2.top - rect1.bottom : rect2.left - rect1.right)
    const gapOffset = gap / 2

    // element padding, which affects flex calculations. :-(
    const pad1 = getPadding(pane1El)[direction]
    const pad2 = getPadding(pane2El)[direction]

    // Inner size is what's actually available for resizing, accounting for gap + padding.
    const outerSize = pageMax - pageMin
    const innerSize = outerSize - gap - pad1 - pad2

    // Figure out active percentage we can update by taking out percentages allocated to other panes.
    let activePercent = (sizes || []).reduce((total, size, index) => {
      if (index === pane1 || index === pane2 || size.units !== "%") return total
      return total - size.value
    }, 100)
    // TESTME: make sure activePercent is at least minPercent * 2???
    activePercent = Math.max(activePercent, minPercent * 2)
    // max percent values for either pane
    const maxPercent = activePercent - minPercent

    // We don't need to return them all, but it's helpful for debugging to lay them all out like this
    return {
      pane1,
      pane2,
      direction,
      pageMin,
      pageMax,
      outerSize,
      innerSize,
      gap,
      gapOffset,
      pad1,
      pad2,
      activePercent,
      minPercent,
      maxPercent
    }
  }

  /**
   * Return the mouse position for resizing, relative to our `direction`.
   */
  getMousePosition(event: MouseEvent): number {
    return this.direction === "vertical" ? event.pageY : event.pageX
  }

  /** Cached dimensions calculated `onMouseDown`. */
  dimensions: SplitPanelDimensions | undefined

  /**
   * `onMouseDown` `event` handler.  This just sets things up.
   */
  onMouseDown = (event: React.MouseEvent<HTMLDivElement>, pane1: number, pane2: number): void => {
    // Calculate sizing dimensions up-front, so mousemove can be fast.
    try {
      this.dimensions = this.getSizingDimensions(pane1, pane2)
      console.info("<SplitPanel> onMouseDown:", "\n\tpanel:", this, "\n\tdimensions: ", this.dimensions)
    } catch (e) {
      console.error("<SplitPanel> got error figuring dimensions:", e)
      return
    }
    // add mouseup / mousemove event handlers to actualy do the work
    document.addEventListener("mouseup", this.onMouseUp)
    document.addEventListener("mousemove", this.onMouseMove)
    // we got this
    event.preventDefault()
    event.stopPropagation()
  }

  /**
   * `onMouseMove` `event` handler. This does the actual resizing.
   */
  onMouseMove = (event: MouseEvent): void => {
    const { dimensions, sizes } = this
    if (!dimensions || !sizes) return
    const { pane1, pane2, pageMin, gapOffset, innerSize, activePercent, minPercent, maxPercent } = dimensions
    const mousePosition = this.getMousePosition(event)
    // if either of these is not a number, we can't figure anything out
    if (isNaN(innerSize) || isNaN(mousePosition)) return
    // adjust global mouse coordinate for panel start + gap, so gap is centered under the mouse
    const adjustedMousePosition = mousePosition - pageMin - gapOffset
    // get raw value for first pane
    let pane1Value = (adjustedMousePosition * activePercent) / innerSize
    // round and clamp value between minPercent and maxPercent
    pane1Value = Math.min(maxPercent, Math.max(minPercent, pane1Value))
    // go to 2 digits of precision
    pane1Value = Math.round(pane1Value * 100) / 100
    // other pane gets what's left, also with 2 digits of precision
    const pane2Value = Math.round((activePercent - pane1Value) * 100) / 100
    // actually adjust the sizes
    const newSizes = sizes.map((size, index) => {
      if (index === pane1) return { ...size, value: pane1Value, units: "%" }
      if (index === pane2) return { ...size, value: pane2Value, units: "%" }
      return size
    })
    this.updateSizes(newSizes)
    // console.info({ mousePosition, adjustedMousePosition, innerSize, activePercent, pane1Value, pane2Value })
  }

  /**
   * `onMouseUp` `event` handler. This cleans things up.
   */
  onMouseUp = (_event: MouseEvent): void => {
    console.info("<SplitPanel> onMouseUp: new sizes", this.sizes)
    // Clean up event handlers
    document.removeEventListener("mouseup", this.onMouseUp)
    document.removeEventListener("mousemove", this.onMouseMove)
  }
}

////////////////
// ## Sub-components
////////////////

/** Props for `<SplitPane>`. */
export type SplitPaneProps = React.ComponentPropsWithoutRef<"div"> & {
  /** Pane content. */
  children?: ReactNode
  /** Add border around pane. */
  bordered?: boolean
  /** Add padding: `true`, `"tightly"` or `"loosely"`. */
  padded?: boolean | "tightly" | "loosely"
  /** Show white background and shadow. */
  light?: boolean
  /** Round corners. */
  rounded?: boolean
  /** Add auto-scrolling. */
  scrolling?: boolean
}

/****************
 * ### `<SplitPane>`
 * Single pane in a `<SplitPanel />`.
 * You don't need to create these, but you can if you want one particular panel
 * to override `bordered` etc set at the panel-level.
 ****************/
export class SplitPane extends React.PureComponent<SplitPaneProps> {
  /** Render pane `div`, translating `bordered`/`padded`/`light`/`rounded`/`scrolling` into classNames. */
  render() {
    const {
      children,
      bordered = false, // add border
      padded = false, // add padding, `true`, `tightly` or loosely`
      light = false, // show white background and shadow
      rounded = false, // round corners
      scrolling = false, // add auto-scrolling
      ...props // including `id`, `style`, `className` (dealt with below), aria stuff...
    } = this.props

    const className = classnames(
      {
        bordered,
        tightly: padded === "tightly",
        loosely: padded === "loosely",
        padded,
        light,
        rounded,
        scrolling
      },
      "SplitPanelPane",
      props.className // put provided className at the end so it will win
    )
    return (
      <div {...props} className={className}>
        {children}
      </div>
    )
  }
}
SplitPanel.Pane = SplitPane

/****************
 * ### `<SplitSpacer>`
 * Spacer auto-added between elements for `<SplitPanel spaced />` if not `resizable`.
 ****************/
export function SplitSpacer() {
  return <div className="Spacer" />
}
SplitPanel.Spacer = SplitSpacer

/** Props for `<SplitSizer>`. */
export type SplitSizerProps = {
  /** `onMouseDown` handler; `<SplitPanel>` wires this up to start a resize drag. */
  onMouseDown: (event: React.MouseEvent<HTMLDivElement>) => void
}

/****************
 * ### `<SplitSizer>`
 * Sizer auto-added between elements for `<SplitPanel resizable />`.
 ****************/
export function SplitSizer({ onMouseDown }: SplitSizerProps) {
  return <div className="SplitPanelSizer" onMouseDown={onMouseDown} />
}
SplitPanel.Sizer = SplitSizer

// TODO:
// - Check `hidden` of childen and drop as necessary (must be set in <SplitPanel> context).
// - SplitPanel: `minSize` and/or `maxSizes` as percentage.
// - SplitPane: `collapsible`
// - SplitPane `fixed` so never resizable?
// - Responsive sizing or alternative layouts for devices.
// - `position:absolute` on pane child is a bit dodgy... ??
// - test sizing logic in other browsers

/** Props for `<SplitPanel>`. */
export type SplitPanelProps = React.ComponentPropsWithoutRef<"div"> & {
  /** Children, auto-wrapped in `<SplitPane>` unless already one (or another `<SplitPanel>`). */
  children?: ReactNode
  /** Column sizes for horizontal split, as `true`, string or array.  See `normalizeSizes()`. */
  columns?: PanelSizeSpec
  /** Row sizes for vertical split, as `true`, string or array.  See `normalizeSizes()`. */
  rows?: PanelSizeSpec
  /** Fill container in alternate axis. */
  fluid?: boolean
  /** Spacing around and between children.  `true`, `"tightly"` or `"loosely"`. */
  spaced?: boolean | "tightly" | "loosely"
  /** Provide resize bars.  Will store `sizes` as preference if element has an `id`. */
  resizable?: boolean
  /** Minimum percent size for resizable panels. */
  minSize?: number

  // The following will be passed down to SplitPanes which are automatically created.
  // If you create a <SplitPane> manually, these settings are ignored.
  /** Panes are bordered. */
  bordered?: boolean
  /** Padding in panes. */
  padded?: boolean | "tightly" | "loosely"
  /** Panes appear light. */
  light?: boolean
  /** Panes appear rounded. */
  rounded?: boolean
  /** Provide scrollbars in panes. */
  scrolling?: boolean
}

/** `columns`/`rows` size spec: `true` for equal sizes, a `"20%,2em,*"` string, or an array of sizes. */
type PanelSizeSpec = boolean | string | Array<string | number>

/**
 * A single normalized panel size, e.g. `{ value: 20, units: "%" }`.
 */
type PanelSize = {
  /** Numeric magnitude, interpreted per `units`. */
  value: number
  /** `px`, `em`, `rem` or `%`. */
  units: string
}

/** Sizing geometry calculated `onMouseDown`, used to do fast `onMouseMove` math. */
type SplitPanelDimensions = {
  /** Index of first pane in resize pair. */
  pane1: number
  /** Index of second pane in resize pair. */
  pane2: number
  /** Panel's `direction`, cached for the drag. */
  direction: "horizontal" | "vertical"
  /** Page-coordinate start of resize region (`pane1`'s `top`/`left`). */
  pageMin: number
  /** Page-coordinate end of resize region (`pane2`'s `bottom`/`right`). */
  pageMax: number
  /** `pageMax - pageMin`. */
  outerSize: number
  /** Space actually usable for resizing, after subtracting `gap` and padding. */
  innerSize: number
  /** Gap between the two panes, in pixels. */
  gap: number
  /** Half of `gap`, so the gap stays centered under the mouse while dragging. */
  gapOffset: number
  /** `pane1`'s padding along `direction`. */
  pad1: number
  /** `pane2`'s padding along `direction`. */
  pad2: number
  /** Total percent available to redistribute between `pane1`/`pane2`. */
  activePercent: number
  /** Minimum percent size for a pane, from panel's `minSize`. */
  minPercent: number
  /** Maximum percent one pane can take: `activePercent - minPercent`. */
  maxPercent: number
}

// packages/app/src/solid/SplitPanel.tsx
import { For, Show, children, createEffect, omit, onCleanup } from "solid-js"
import type { JSX } from "@solidjs/web"

import { getPref, setPref } from "$/util"

import "./spell.css"
import "./SplitPanel.css"

/****************
 * ### `<SplitPanel>`
 * Lays its `children` out in a row (`columns`) or a column (`rows`) of panes, sized as `columns` / `rows` say;
 * `resizable` puts a bar between each two you drag to resize them.  Look:  `SplitPanel.css`.
 * - Sizes, as EITHER `rows` or `columns`:
 *   - `true`:  every pane the same size
 *   - an array, e.g. `["20%", "20%", "*", 100]`, or a string, e.g. `"30%,2em"`
 *   - a number, or `px` / `em` / `rem`:  a fixed size
 *   - `%`:  that share of the space the fixed panes leave
 *   - `*`, or missing:  an equal share of the percent left, e.g. `"80%"` ~== `"80%,20%"` for two panes,
 *     `"*,*,200px"` ~== `"50%,50%,200px"`
 * - Each child becomes a pane:  wrapped in a `<SplitPane>` with the panel's `bordered`, `padded`, `light`,
 *   `rounded` and `scrolling`.  A child that IS a `<SplitPane>` (its own look) or a nested `<SplitPanel>` is a pane
 *   as it is.
 *   - NOTE: one pane per DOM node the children draw:  a child component drawing two top-level nodes makes two
 *     panes.  The editor's panes each draw one `<div>`.
 * - `spaced`:  room around the panes, and a spacer between them unless `resizable`.
 * - With an `id`, a resizable panel remembers its sizes as a preference under that id (`$/util`'s `setPref()`):
 *   make it unique in the app.
 * - Sizes are applied as each pane's inline `flex`, NOT drawn by Solid:  a drag rewrites them on every mouse move.
 ****************/
export function SplitPanel(props: SplitPanelProps) {
  let panel: HTMLDivElement | undefined
  const kids = children(() => props.children)
  /** Sizes now, one per pane.  NOT a signal:  a drag rewrites them on every mouse move. */
  let sizes: PanelSize[] = []
  /** What a drag works from, measured when it starts. */
  let dragging: SplitPanelDimensions | undefined

  // size the panes once drawn, and again when their number or the size spec changes
  createEffect(
    () => ({ count: kids.toArray().length, columns: props.columns, rows: props.rows, id: props.id }),
    ({ count, columns, rows, id }) => {
      if (!columns === !rows) console.warn("<SplitPanel>s need exactly one of 'columns' or 'rows'.", id)
      const stored = id ? (getPref(id, undefined) as string | undefined) : undefined
      apply(normalizeSizes(stored || (columns ?? rows), count), false)
    }
  )
  onCleanup(stopDragging)

  return (
    <div
      ref={(element) => {
        panel = element
      }}
      {...omit(props, ...PANEL_PROPS, "class", "children")}
      class={[
        "SplitPanel",
        props.columns ? "horizontal" : "vertical",
        {
          fluid: !!props.fluid,
          spaced: !!props.spaced,
          tightly: props.spaced === "tightly",
          loosely: props.spaced === "loosely",
          resizable: !!props.resizable
        },
        props.class
      ]}
    >
      <For each={kids.toArray()}>
        {(child, index) => (
          <>
            <Show when={index() > 0}>
              <Show
                when={props.resizable}
                fallback={
                  <Show when={props.spaced}>
                    <SplitSpacer />
                  </Show>
                }
              >
                <SplitSizer onMouseDown={(event) => startDragging(event, index() - 1, index())} />
              </Show>
            </Show>
            {isPane(child) ? (
              child
            ) : (
              <SplitPane
                bordered={props.bordered}
                padded={props.padded}
                light={props.light}
                rounded={props.rounded}
                scrolling={props.scrolling}
              >
                {child}
              </SplitPane>
            )}
          </>
        )}
      </For>
    </div>
  )

  /** The panes, in order:  wrapped children, `<SplitPane>`s and nested `<SplitPanel>`s. */
  function paneElements(): HTMLElement[] {
    return panel ? ([...panel.children].filter(isPane) as HTMLElement[]) : []
  }

  /**
   * Make `next` the sizes:  each pane's inline `flex`.
   * - `save`:  remember them as the `id` preference, e.g. after a drag.
   */
  function apply(next: PanelSize[], save = true) {
    sizes = next
    if (save && props.id) setPref(props.id, sizeString(sizes))
    paneElements().forEach((pane, index) => {
      const size = sizes[index]
      if (!size) return
      pane.style.flex = size.units === "%" ? `${size.value} ${size.value} 0` : `0 0 ${size.value}${size.units}`
    })
  }

  /**
   * A sizer's `mousedown`:  measure the two panes it sits between, then follow the mouse until it's let go.
   * - Measures ONCE, here:  `getBoundingClientRect()` is too slow for every mouse move.  So scrolling the page
   *   mid-drag would throw it off.
   */
  function startDragging(event: MouseEvent, pane1: number, pane2: number) {
    try {
      dragging = measure(paneElements(), sizes, pane1, pane2, props.columns ? "horizontal" : "vertical", minPercent())
    } catch (error) {
      console.error("<SplitPanel> couldn't measure its panes:", error)
      return
    }
    document.addEventListener("mousemove", drag)
    document.addEventListener("mouseup", stopDragging)
    event.preventDefault()
    event.stopPropagation()
  }

  /** `mousemove` while dragging:  resize the two panes so the gap between them is under the mouse. */
  function drag(event: MouseEvent) {
    if (!dragging) return
    const { pane1, pane2, direction, pageMin, gapOffset, innerSize, activePercent, minPercent, maxPercent } = dragging
    const mouse = direction === "vertical" ? event.pageY : event.pageX
    if (isNaN(innerSize) || isNaN(mouse)) return
    // the first pane's share, clamped, to 2 decimals;  the second gets what's left
    let value1 = ((mouse - pageMin - gapOffset) * activePercent) / innerSize
    value1 = Math.round(Math.min(maxPercent, Math.max(minPercent, value1)) * 100) / 100
    const value2 = Math.round((activePercent - value1) * 100) / 100
    apply(
      sizes.map((size, index) => {
        if (index === pane1) return { value: value1, units: "%" }
        if (index === pane2) return { value: value2, units: "%" }
        return size
      })
    )
  }

  /** `mouseup`, or unmounted:  stop following the mouse. */
  function stopDragging() {
    dragging = undefined
    document.removeEventListener("mousemove", drag)
    document.removeEventListener("mouseup", stopDragging)
  }

  /** Smallest share a pane may have, in percent. */
  function minPercent() {
    return props.minSize || 5
  }
}

/** Props for `<SplitPanel>`:  these, plus any `<div>` attribute. */
export type SplitPanelProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, "children"> & {
  /** The panes:  any content, one pane per node it draws. */
  children?: JSX.Element
  /** Sizes across, for panes side by side:  `true`, a string or an array.  See `<SplitPanel>`. */
  columns?: PanelSizeSpec
  /** Sizes down, for panes one above the other:  `true`, a string or an array.  See `<SplitPanel>`. */
  rows?: PanelSizeSpec
  /** Fill the container the other way. */
  fluid?: boolean
  /** Room around and between the panes:  `true`, `"tightly"` or `"loosely"`. */
  spaced?: boolean | "tightly" | "loosely"
  /** Bars to drag between the panes;  sizes remembered under `id`. */
  resizable?: boolean
  /** Smallest share a pane may be dragged to, in percent.  Default:  `5`. */
  minSize?: number
  /** Wrapped panes are bordered. */
  bordered?: boolean
  /** Padding in wrapped panes:  `true`, `"tightly"` or `"loosely"`. */
  padded?: boolean | "tightly" | "loosely"
  /** Wrapped panes are light. */
  light?: boolean
  /** Wrapped panes are rounded. */
  rounded?: boolean
  /** Wrapped panes scroll. */
  scrolling?: boolean
}

/** `<SplitPanel>`'s own props, never passed to the `<div>`. */
const PANEL_PROPS = [
  "columns",
  "rows",
  "fluid",
  "spaced",
  "resizable",
  "minSize",
  "bordered",
  "padded",
  "light",
  "rounded",
  "scrolling"
] as const

/****************
 * ### `<SplitPane>`
 * One pane of a `<SplitPanel>`:  write one yourself to give a pane its own look, else the panel wraps each child
 * in one.  Its one child fills it (`SplitPanel.css`).
 ****************/
export function SplitPane(props: SplitPaneProps) {
  return (
    <div
      {...omit(props, "bordered", "padded", "light", "rounded", "scrolling", "class", "children")}
      class={[
        "SplitPanelPane",
        {
          bordered: !!props.bordered,
          padded: !!props.padded,
          tightly: props.padded === "tightly",
          loosely: props.padded === "loosely",
          light: !!props.light,
          rounded: !!props.rounded,
          scrolling: !!props.scrolling
        },
        props.class
      ]}
    >
      {props.children}
    </div>
  )
}

/** Props for `<SplitPane>`:  these, plus any `<div>` attribute. */
export type SplitPaneProps = JSX.HTMLAttributes<HTMLDivElement> & {
  /** A border around the pane. */
  bordered?: boolean
  /** Padding:  `true`, `"tightly"` or `"loosely"`. */
  padded?: boolean | "tightly" | "loosely"
  /** White background and a shadow. */
  light?: boolean
  /** Round corners. */
  rounded?: boolean
  /** Scrolls its content. */
  scrolling?: boolean
}

/****************
 * ### `<SplitSpacer>`
 * Room between two panes of a `spaced`, not `resizable`, `<SplitPanel>`.
 ****************/
export function SplitSpacer() {
  return <div class="Spacer" />
}

/****************
 * ### `<SplitSizer>`
 * The bar between two panes of a `resizable` `<SplitPanel>`:  drag it to resize them.
 ****************/
export function SplitSizer(props: { onMouseDown: (event: MouseEvent) => void }) {
  return <div class="SplitPanelSizer" onMouseDown={(event) => props.onMouseDown(event)} />
}

////////////////
// ## Sizes
////////////////

/** `columns` / `rows`:  `true` for equal sizes, a `"20%,2em,*"` string, or an array of sizes. */
export type PanelSizeSpec = boolean | string | Array<string | number>

/** One pane's size, e.g. `{ value: 20, units: "%" }`. */
export type PanelSize = {
  /** How much, in `units`. */
  value: number
  /** `px`, `em`, `rem` or `%`. */
  units: string
}

/** One size in a spec:  a number with optional units, e.g. `20`, `20px`, `20%`. */
const NUM_WITH_UNITS = /^([0-9]*\.?[0-9]+)(px|em|rem|%)?$/

/**
 * One `PanelSize` per pane from `spec` (`columns` / `rows`, or a stored preference):  cut or padded to `count`,
 * a missing or unreadable entry counting as `*`.
 * - `*` entries share the percent the `%` entries leave, equally (at least 1% each).
 */
export function normalizeSizes(spec: unknown, count: number): PanelSize[] {
  let input: (string | number)[]
  if (typeof spec === "string" && spec) input = spec.split(",")
  else if (Array.isArray(spec)) input = spec as (string | number)[]
  else input = []
  const raw: (string | number)[] = input.slice(0, count)
  while (raw.length < count) raw.push("*")

  let stars = 0
  let percents = 0
  const sizes = raw.map((size): { value: number | "*"; units: string } => {
    if (typeof size === "number") return { value: size, units: "px" }
    if (size !== "*") {
      const match = NUM_WITH_UNITS.exec(size.trim())
      if (match) {
        const units = match[2] || "px"
        const value = parseFloat(match[1])
        if (units === "%") percents += value
        return { value, units }
      }
      console.warn(`<SplitPanel> size '${size}' not understood`)
    }
    stars++
    return { value: "*", units: "%" }
  })
  const perStar = Math.max(1, (100 - percents) / Math.max(stars, 1))
  return sizes.map(({ value, units }) => ({ value: value === "*" ? perStar : value, units }))
}

/** `sizes` as a spec string, e.g. `"60%,40%"`:  how a preference stores them. */
function sizeString(sizes: PanelSize[]): string {
  return sizes.map(({ value, units }) => `${value}${units}`).join(",")
}

/** Is `node` a pane of a `<SplitPanel>` as it is:  a `<SplitPane>`, or a nested `<SplitPanel>`? */
function isPane(node: unknown): node is HTMLElement {
  return (
    node instanceof HTMLElement && (node.classList.contains("SplitPanelPane") || node.classList.contains("SplitPanel"))
  )
}

/**
 * What a drag between `pane1` and `pane2` works from, measured from the DOM.
 * - Throws if the panes aren't drawn:  `startDragging()` catches it.
 * - TODO: off if a CSS transform applies to the panel.
 */
function measure(
  panes: HTMLElement[],
  sizes: PanelSize[],
  pane1: number,
  pane2: number,
  direction: "horizontal" | "vertical",
  minPercent: number
): SplitPanelDimensions {
  const rect1 = panes[pane1].getBoundingClientRect()
  const rect2 = panes[pane2].getBoundingClientRect()
  const vertical = direction === "vertical"
  // page coordinates:  the mouse's `pageX` / `pageY` are too
  const scroll = vertical ? window.scrollY : window.scrollX
  const pageMin = (vertical ? rect1.top : rect1.left) + scroll
  const pageMax = (vertical ? rect2.bottom : rect2.right) + scroll
  // the gap between the panes, kept centred under the mouse
  const gap = Math.ceil(vertical ? rect2.top - rect1.bottom : rect2.left - rect1.right)
  // padding counts in the panes' `flex` sizes
  const pad1 = padding(panes[pane1], vertical)
  const pad2 = padding(panes[pane2], vertical)
  const innerSize = pageMax - pageMin - gap - pad1 - pad2
  // the percent the two share:  100, less the other `%` panes'
  const othersPercent = sizes.reduce(
    (total, size, index) => (index === pane1 || index === pane2 || size.units !== "%" ? total : total + size.value),
    0
  )
  const activePercent = Math.max(100 - othersPercent, minPercent * 2)
  return {
    pane1,
    pane2,
    direction,
    pageMin,
    gapOffset: gap / 2,
    innerSize,
    activePercent,
    minPercent,
    maxPercent: activePercent - minPercent
  }
}

/**
 * `element`'s padding along a direction, px:  top + bottom when `vertical`, else left + right.
 * - Read from `getComputedStyle()` directly:  `$/util`'s old `getPadding()` read `NaN` in the browser test project.
 */
function padding(element: HTMLElement, vertical: boolean): number {
  const style = getComputedStyle(element)
  return vertical
    ? parseFloat(style.paddingTop) + parseFloat(style.paddingBottom)
    : parseFloat(style.paddingLeft) + parseFloat(style.paddingRight)
}

/** What a drag works from, measured once when it starts (`measure()`). */
type SplitPanelDimensions = {
  /** Index of the pane before the sizer. */
  pane1: number
  /** Index of the pane after it. */
  pane2: number
  /** Across (`horizontal`) or down (`vertical`). */
  direction: "horizontal" | "vertical"
  /** Page coordinate where `pane1` starts. */
  pageMin: number
  /** Half the gap between the panes, so the gap stays centred under the mouse. */
  gapOffset: number
  /** Room the two panes share, less the gap and their padding, px. */
  innerSize: number
  /** Percent the two panes share. */
  activePercent: number
  /** Smallest share either may have, percent. */
  minPercent: number
  /** Largest share either may have:  `activePercent - minPercent`. */
  maxPercent: number
}
